import cadquery as cq
import json
import argparse


def build(params):
    """Implicit lattice hyperobject stub.

    The real TPMS geometry is generated by the implicit engine, not OpenSCAD
    or CadQuery.  This file provides a CadQuery-compatible placeholder so
    that the headless render pipeline can produce a bounding-volume proxy
    for any project that declares ``engine: implicit``.
    """
    size = float(params.get('size', 10.0))

    result = cq.Workplane("XY").box(size, size, size)
    return result.clean()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--params", type=str, default="{}")
    parser.add_argument("--out", type=str, default="out.stl")
    args = parser.parse_args()

    params = json.loads(args.params)
    res = build(params)

    if args.out:
        cq.exporters.export(res, args.out)
